apiVersion: v1
kind: Pod
metadata:
  name: probe-pod
spec:
  containers:
    - name: my-actuator
      image: my-actuator
      imagePullPolicy: Never
      livenessProbe:
        httpGet:
          path: /actuator/health/liveness
          port: 8090
        initialDelaySeconds: 30
      readinessProbe:
        httpGet:
          path: /actuator/health/readiness
          port: 8090
        initialDelaySeconds: 30
      ports:
        - containerPort: 8080