server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoint:
    health:
      show-components: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: 8090
  prometheus:
    metrics:
      export:
        enabled: true
